### PR TITLE
add redux functionality and immutable data

### PR DESCRIPTION
**Pull request by flipace**

### CODE REVIEW

**Comment by mateuszmazurek** [comment]
When do you plan to merge this into `master`? Will your `lovely.js` boilerplate need any changes to work with next `horizon-react` version?

**Comment by flipace** [comment]
hi @mateuszmazurek I hope to merge this in the next 2-3 weeks. There are still a couple of things which I want to add (easier composition of queries until horizon supports joins for example) before merging.

I also want to add a few small things so that existing apps don't have to change anything for the new version.

**Comment by mateuszmazurek** [comment]
@flipace glad to hear it, thx :)

**Comment by daniel1943** [comment]
Hi, looking forward to redux integration... Is next branch ready to use :) ?
Cheers

**Comment by flipace** [comment]
hi @daniel1943 

i didn't have the time yet to work on this. as soon as this is ready, i'll make sure to ping you!

**Pull request closed without merging**
